name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Verify Vite installation
        run: npm list vite

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "shailendrastha7@gmail.com"
          git config --global user.name "ShailendraDev7"

      - name: Checkout main branch
        run: |
          git fetch origin
          git checkout main || git checkout -b main
          git pull origin main || echo "main branch created"

      - name: Copy build files
        run: |
          git rm -rf .
          cp -r dist/* .
          touch .nojekyll  # If deploying to GitHub Pages

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          git commit -m "Deploy to main"
          git push origin main
