name: Build and Deploy

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to main
        run: |
          git config --global user.email "shailendrastha7@gmail.com"
          git config --global user.name "ShailendraDev7"
          git checkout main
          git rm -rf .
          cp -r dist/* .
          git add .
          git commit -m "Deploy to main"
          git push origin main
